/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsUpdate } from "../../funcs/collectionsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V3CollectionsCrudUpdateRequest$inboundSchema,
};

export const tool$collectionsUpdate: ToolDefinition<typeof args> = {
  name: "collections-update",
  description: `Update a collection

Update a collection's name, description, and/or query.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
