/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { globalDataGetCertificate } from "../../funcs/globalDataGetCertificate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.V3GlobaldataAssetCertificateRequest$inboundSchema,
};

export const tool$globalDataGetCertificate: ToolDefinition<typeof args> = {
  name: "global-data-get-certificate",
  description: `Asset / Certificate

Get a Certificate`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await globalDataGetCertificate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
