workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    converge-source:
        inputs:
            - location: https://github.com/censys/censys-sdk-openapi/releases/latest/download/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/censys/censys/converge-source
targets:
    censys-sdk-typescript:
        target: typescript
        source: converge-source
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/censys/censys/converge-source-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
