/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3AccountmanagementRemoveOrgMemberRequest = {
  /**
   * The ID of a Censys organization. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
   */
  organizationId: string;
  /**
   * The ID of a Censys user. You can obtain a user's ID by listing members of an organization.
   */
  userId: string;
};

export type V3AccountmanagementRemoveOrgMemberResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type V3AccountmanagementRemoveOrgMemberRequest$Outbound = {
  organization_id: string;
  user_id: string;
};

/** @internal */
export const V3AccountmanagementRemoveOrgMemberRequest$outboundSchema:
  z.ZodType<
    V3AccountmanagementRemoveOrgMemberRequest$Outbound,
    z.ZodTypeDef,
    V3AccountmanagementRemoveOrgMemberRequest
  > = z.object({
    organizationId: z.string(),
    userId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      userId: "user_id",
    });
  });

export function v3AccountmanagementRemoveOrgMemberRequestToJSON(
  v3AccountmanagementRemoveOrgMemberRequest:
    V3AccountmanagementRemoveOrgMemberRequest,
): string {
  return JSON.stringify(
    V3AccountmanagementRemoveOrgMemberRequest$outboundSchema.parse(
      v3AccountmanagementRemoveOrgMemberRequest,
    ),
  );
}

/** @internal */
export const V3AccountmanagementRemoveOrgMemberResponse$inboundSchema:
  z.ZodType<V3AccountmanagementRemoveOrgMemberResponse, z.ZodTypeDef, unknown> =
    z.object({
      Headers: z.record(z.array(z.string())).default({}),
    }).transform((v) => {
      return remap$(v, {
        "Headers": "headers",
      });
    });

export function v3AccountmanagementRemoveOrgMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3AccountmanagementRemoveOrgMemberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3AccountmanagementRemoveOrgMemberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3AccountmanagementRemoveOrgMemberResponse' from JSON`,
  );
}
