/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3CollectionsListEventsGlobals = {
  organizationId?: string | undefined;
};

export const ChangeTypes = {
  Asset: "asset",
  Status: "status",
} as const;
export type ChangeTypes = ClosedEnum<typeof ChangeTypes>;

export const AssetChangeTypes = {
  Added: "added",
  Removed: "removed",
} as const;
export type AssetChangeTypes = ClosedEnum<typeof AssetChangeTypes>;

export const StatusChangeTypes = {
  Active: "active",
  Archived: "archived",
  Paused: "paused",
  Populating: "populating",
} as const;
export type StatusChangeTypes = ClosedEnum<typeof StatusChangeTypes>;

export type V3CollectionsListEventsRequest = {
  /**
   * The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
   */
  organizationId?: string | undefined;
  /**
   * The UID for the collection. Obtain the collection ID using the [list collections endpoint](https://docs.censys.com/reference/v3-collections-crud-list#/) or via the collection URL when using the web console.
   */
  collectionUid: string;
  /**
   * Amount of results to return per page.
   */
  pageSize?: number | undefined;
  /**
   * Page token for the requested page of collection results.
   */
  pageToken?: string | undefined;
  /**
   * Change types
   */
  changeTypes?: Array<ChangeTypes> | null | undefined;
  /**
   * Asset change types
   */
  assetChangeTypes?: Array<AssetChangeTypes> | null | undefined;
  /**
   * Status change types
   */
  statusChangeTypes?: Array<StatusChangeTypes> | null | undefined;
  /**
   * Start time of the host timeline
   */
  startTime?: Date | undefined;
  /**
   * End time of the host timeline
   */
  endTime?: Date | undefined;
};

export type V3CollectionsListEventsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ResponseEnvelopeCollectionEventsResponse;
};

/** @internal */
export const ChangeTypes$outboundSchema: z.ZodNativeEnum<typeof ChangeTypes> = z
  .nativeEnum(ChangeTypes);

/** @internal */
export const AssetChangeTypes$outboundSchema: z.ZodNativeEnum<
  typeof AssetChangeTypes
> = z.nativeEnum(AssetChangeTypes);

/** @internal */
export const StatusChangeTypes$outboundSchema: z.ZodNativeEnum<
  typeof StatusChangeTypes
> = z.nativeEnum(StatusChangeTypes);

/** @internal */
export type V3CollectionsListEventsRequest$Outbound = {
  organization_id?: string | undefined;
  collection_uid: string;
  page_size?: number | undefined;
  page_token?: string | undefined;
  change_types?: Array<string> | null | undefined;
  asset_change_types?: Array<string> | null | undefined;
  status_change_types?: Array<string> | null | undefined;
  start_time?: string | undefined;
  end_time?: string | undefined;
};

/** @internal */
export const V3CollectionsListEventsRequest$outboundSchema: z.ZodType<
  V3CollectionsListEventsRequest$Outbound,
  z.ZodTypeDef,
  V3CollectionsListEventsRequest
> = z.object({
  organizationId: z.string().optional(),
  collectionUid: z.string(),
  pageSize: z.number().int().optional(),
  pageToken: z.string().optional(),
  changeTypes: z.nullable(z.array(ChangeTypes$outboundSchema)).optional(),
  assetChangeTypes: z.nullable(z.array(AssetChangeTypes$outboundSchema))
    .optional(),
  statusChangeTypes: z.nullable(z.array(StatusChangeTypes$outboundSchema))
    .optional(),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  endTime: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    collectionUid: "collection_uid",
    pageSize: "page_size",
    pageToken: "page_token",
    changeTypes: "change_types",
    assetChangeTypes: "asset_change_types",
    statusChangeTypes: "status_change_types",
    startTime: "start_time",
    endTime: "end_time",
  });
});

export function v3CollectionsListEventsRequestToJSON(
  v3CollectionsListEventsRequest: V3CollectionsListEventsRequest,
): string {
  return JSON.stringify(
    V3CollectionsListEventsRequest$outboundSchema.parse(
      v3CollectionsListEventsRequest,
    ),
  );
}

/** @internal */
export const V3CollectionsListEventsResponse$inboundSchema: z.ZodType<
  V3CollectionsListEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.ResponseEnvelopeCollectionEventsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function v3CollectionsListEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3CollectionsListEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3CollectionsListEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3CollectionsListEventsResponse' from JSON`,
  );
}
