/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3TagsDeleteTagGlobals = {
  organizationId?: string | undefined;
};

export type V3TagsDeleteTagRequest = {
  /**
   * The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
   */
  organizationId?: string | undefined;
  /**
   * The ID of the tag to delete.
   */
  tagId: string;
};

export type V3TagsDeleteTagResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type V3TagsDeleteTagRequest$Outbound = {
  organization_id?: string | undefined;
  tag_id: string;
};

/** @internal */
export const V3TagsDeleteTagRequest$outboundSchema: z.ZodType<
  V3TagsDeleteTagRequest$Outbound,
  z.ZodTypeDef,
  V3TagsDeleteTagRequest
> = z.object({
  organizationId: z.string().optional(),
  tagId: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    tagId: "tag_id",
  });
});

export function v3TagsDeleteTagRequestToJSON(
  v3TagsDeleteTagRequest: V3TagsDeleteTagRequest,
): string {
  return JSON.stringify(
    V3TagsDeleteTagRequest$outboundSchema.parse(v3TagsDeleteTagRequest),
  );
}

/** @internal */
export const V3TagsDeleteTagResponse$inboundSchema: z.ZodType<
  V3TagsDeleteTagResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function v3TagsDeleteTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3TagsDeleteTagResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3TagsDeleteTagResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3TagsDeleteTagResponse' from JSON`,
  );
}
