/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3ThreathuntingInvestigationsJobsCreateGlobals = {
  organizationId?: string | undefined;
};

export type V3ThreathuntingInvestigationsJobsCreateRequest = {
  /**
   * The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
   */
  organizationId?: string | undefined;
  createInvestigationJobInputBody: components.CreateInvestigationJobInputBody;
};

export type V3ThreathuntingInvestigationsJobsCreateResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ResponseEnvelopeCreatedInvestigationJob;
};

/** @internal */
export type V3ThreathuntingInvestigationsJobsCreateRequest$Outbound = {
  organization_id?: string | undefined;
  CreateInvestigationJobInputBody:
    components.CreateInvestigationJobInputBody$Outbound;
};

/** @internal */
export const V3ThreathuntingInvestigationsJobsCreateRequest$outboundSchema:
  z.ZodType<
    V3ThreathuntingInvestigationsJobsCreateRequest$Outbound,
    z.ZodTypeDef,
    V3ThreathuntingInvestigationsJobsCreateRequest
  > = z.object({
    organizationId: z.string().optional(),
    createInvestigationJobInputBody:
      components.CreateInvestigationJobInputBody$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      createInvestigationJobInputBody: "CreateInvestigationJobInputBody",
    });
  });

export function v3ThreathuntingInvestigationsJobsCreateRequestToJSON(
  v3ThreathuntingInvestigationsJobsCreateRequest:
    V3ThreathuntingInvestigationsJobsCreateRequest,
): string {
  return JSON.stringify(
    V3ThreathuntingInvestigationsJobsCreateRequest$outboundSchema.parse(
      v3ThreathuntingInvestigationsJobsCreateRequest,
    ),
  );
}

/** @internal */
export const V3ThreathuntingInvestigationsJobsCreateResponse$inboundSchema:
  z.ZodType<
    V3ThreathuntingInvestigationsJobsCreateResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.ResponseEnvelopeCreatedInvestigationJob$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function v3ThreathuntingInvestigationsJobsCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ThreathuntingInvestigationsJobsCreateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ThreathuntingInvestigationsJobsCreateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ThreathuntingInvestigationsJobsCreateResponse' from JSON`,
  );
}
