/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3ThreathuntingScansGetGlobals = {
  organizationId?: string | undefined;
};

export type V3ThreathuntingScansGetRequest = {
  /**
   * The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information.
   */
  organizationId?: string | undefined;
  /**
   * The unique identifier of the tracked scan
   */
  scanId: string;
};

export type V3ThreathuntingScansGetResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ResponseEnvelopeTrackedScan;
};

/** @internal */
export type V3ThreathuntingScansGetRequest$Outbound = {
  organization_id?: string | undefined;
  scan_id: string;
};

/** @internal */
export const V3ThreathuntingScansGetRequest$outboundSchema: z.ZodType<
  V3ThreathuntingScansGetRequest$Outbound,
  z.ZodTypeDef,
  V3ThreathuntingScansGetRequest
> = z.object({
  organizationId: z.string().optional(),
  scanId: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    scanId: "scan_id",
  });
});

export function v3ThreathuntingScansGetRequestToJSON(
  v3ThreathuntingScansGetRequest: V3ThreathuntingScansGetRequest,
): string {
  return JSON.stringify(
    V3ThreathuntingScansGetRequest$outboundSchema.parse(
      v3ThreathuntingScansGetRequest,
    ),
  );
}

/** @internal */
export const V3ThreathuntingScansGetResponse$inboundSchema: z.ZodType<
  V3ThreathuntingScansGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.ResponseEnvelopeTrackedScan$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function v3ThreathuntingScansGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3ThreathuntingScansGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ThreathuntingScansGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ThreathuntingScansGetResponse' from JSON`,
  );
}
