/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { CenseyeJob, CenseyeJob$inboundSchema } from "./censeyejob.js";

export type CenseyeJobsListResponse = {
  /**
   * List of CensEye jobs.
   */
  jobs: Array<CenseyeJob> | null;
  /**
   * Token to retrieve the next page of jobs.
   */
  nextPageToken?: string | undefined;
};

/** @internal */
export const CenseyeJobsListResponse$inboundSchema: z.ZodType<
  CenseyeJobsListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  jobs: z.nullable(z.array(CenseyeJob$inboundSchema)),
  next_page_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "next_page_token": "nextPageToken",
  });
});

export function censeyeJobsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<CenseyeJobsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CenseyeJobsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CenseyeJobsListResponse' from JSON`,
  );
}
