/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CheckpointTopology = {
  commonName?: string | undefined;
  organization?: string | undefined;
};

/** @internal */
export const CheckpointTopology$inboundSchema: z.ZodType<
  CheckpointTopology,
  z.ZodTypeDef,
  unknown
> = z.object({
  common_name: z.string().optional(),
  organization: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "common_name": "commonName",
  });
});

export function checkpointTopologyFromJSON(
  jsonString: string,
): SafeParseResult<CheckpointTopology, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckpointTopology$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckpointTopology' from JSON`,
  );
}
