/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CiscoSdwanVdaemon = {
  deviceRole?: string | undefined;
  deviceUuid?: string | undefined;
  organizationName?: string | undefined;
  siteId?: number | undefined;
};

/** @internal */
export const CiscoSdwanVdaemon$inboundSchema: z.ZodType<
  CiscoSdwanVdaemon,
  z.ZodTypeDef,
  unknown
> = z.object({
  device_role: z.string().optional(),
  device_uuid: z.string().optional(),
  organization_name: z.string().optional(),
  site_id: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "device_role": "deviceRole",
    "device_uuid": "deviceUuid",
    "organization_name": "organizationName",
    "site_id": "siteId",
  });
});

export function ciscoSdwanVdaemonFromJSON(
  jsonString: string,
): SafeParseResult<CiscoSdwanVdaemon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CiscoSdwanVdaemon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CiscoSdwanVdaemon' from JSON`,
  );
}
