/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CobaltStrikePostEx = {
  x64?: string | undefined;
  x86?: string | undefined;
};

/** @internal */
export const CobaltStrikePostEx$inboundSchema: z.ZodType<
  CobaltStrikePostEx,
  z.ZodTypeDef,
  unknown
> = z.object({
  x64: z.string().optional(),
  x86: z.string().optional(),
});

export function cobaltStrikePostExFromJSON(
  jsonString: string,
): SafeParseResult<CobaltStrikePostEx, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CobaltStrikePostEx$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CobaltStrikePostEx' from JSON`,
  );
}
