/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CobaltStrikeConfig,
  CobaltStrikeConfig$inboundSchema,
} from "./cobaltstrikeconfig.js";

export type CobaltStrike = {
  x64?: CobaltStrikeConfig | undefined;
  x86?: CobaltStrikeConfig | undefined;
};

/** @internal */
export const CobaltStrike$inboundSchema: z.ZodType<
  CobaltStrike,
  z.ZodTypeDef,
  unknown
> = z.object({
  x64: CobaltStrikeConfig$inboundSchema.optional(),
  x86: CobaltStrikeConfig$inboundSchema.optional(),
});

export function cobaltStrikeFromJSON(
  jsonString: string,
): SafeParseResult<CobaltStrike, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CobaltStrike$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CobaltStrike' from JSON`,
  );
}
