/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The media type of the file to upload. Send it bare: a type carrying parameters, such as a charset, is not accepted.
 */
export const ContentType = {
  ApplicationPdf: "application/pdf",
  TextHtml: "text/html",
  TextCsv: "text/csv",
  TextPlain: "text/plain",
  ImagePng: "image/png",
  ImageJpeg: "image/jpeg",
  ImageWebp: "image/webp",
} as const;
/**
 * The media type of the file to upload. Send it bare: a type carrying parameters, such as a charset, is not accepted.
 */
export type ContentType = ClosedEnum<typeof ContentType>;

export type CreateInvestigationFileInputBody = {
  /**
   * The media type of the file to upload. Send it bare: a type carrying parameters, such as a charset, is not accepted.
   */
  contentType: ContentType;
  /**
   * The original name of the file. Used only as display metadata on the investigation; it does not affect where the file is stored.
   */
  filename?: string | undefined;
  /**
   * The size of the file in bytes. The largest a single file may be is set by the service and can change; sending more returns an unprocessable entity response. The upload itself is limited independently, so understating this does not raise the limit.
   */
  sizeBytes: number;
};

/** @internal */
export const ContentType$outboundSchema: z.ZodNativeEnum<typeof ContentType> = z
  .nativeEnum(ContentType);

/** @internal */
export type CreateInvestigationFileInputBody$Outbound = {
  content_type: string;
  filename?: string | undefined;
  size_bytes: number;
};

/** @internal */
export const CreateInvestigationFileInputBody$outboundSchema: z.ZodType<
  CreateInvestigationFileInputBody$Outbound,
  z.ZodTypeDef,
  CreateInvestigationFileInputBody
> = z.object({
  contentType: ContentType$outboundSchema,
  filename: z.string().optional(),
  sizeBytes: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    contentType: "content_type",
    sizeBytes: "size_bytes",
  });
});

export function createInvestigationFileInputBodyToJSON(
  createInvestigationFileInputBody: CreateInvestigationFileInputBody,
): string {
  return JSON.stringify(
    CreateInvestigationFileInputBody$outboundSchema.parse(
      createInvestigationFileInputBody,
    ),
  );
}
