/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CursorOnTargetPoint = {
  ce?: number | undefined;
  hae?: number | undefined;
  lat?: number | undefined;
  le?: number | undefined;
  lon?: number | undefined;
};

/** @internal */
export const CursorOnTargetPoint$inboundSchema: z.ZodType<
  CursorOnTargetPoint,
  z.ZodTypeDef,
  unknown
> = z.object({
  ce: z.number().optional(),
  hae: z.number().optional(),
  lat: z.number().optional(),
  le: z.number().optional(),
  lon: z.number().optional(),
});

export function cursorOnTargetPointFromJSON(
  jsonString: string,
): SafeParseResult<CursorOnTargetPoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CursorOnTargetPoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CursorOnTargetPoint' from JSON`,
  );
}
