/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Cwmp = {
  auth?: Array<string> | null | undefined;
  cookies?: Array<string> | null | undefined;
  server?: string | undefined;
};

/** @internal */
export const Cwmp$inboundSchema: z.ZodType<Cwmp, z.ZodTypeDef, unknown> = z
  .object({
    auth: z.nullable(z.array(z.string())).optional(),
    cookies: z.nullable(z.array(z.string())).optional(),
    server: z.string().optional(),
  });

export function cwmpFromJSON(
  jsonString: string,
): SafeParseResult<Cwmp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cwmp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cwmp' from JSON`,
  );
}
