/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DnsEDns = {
  do?: boolean | undefined;
  options?: Array<string> | null | undefined;
  udp?: number | undefined;
  version?: number | undefined;
};

/** @internal */
export const DnsEDns$inboundSchema: z.ZodType<DnsEDns, z.ZodTypeDef, unknown> =
  z.object({
    do: z.boolean().optional(),
    options: z.nullable(z.array(z.string())).optional(),
    udp: z.number().int().optional(),
    version: z.number().int().optional(),
  });

export function dnsEDnsFromJSON(
  jsonString: string,
): SafeParseResult<DnsEDns, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DnsEDns$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DnsEDns' from JSON`,
  );
}
