/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Either A or AAAA.
 */
export const DnsIpResolutionRecordRecordType = {
  A: "A",
  Aaaa: "AAAA",
} as const;
/**
 * Either A or AAAA.
 */
export type DnsIpResolutionRecordRecordType = OpenEnum<
  typeof DnsIpResolutionRecordRecordType
>;

export type DnsIpResolutionRecord = {
  /**
   * The domain name that resolved to this IP.
   */
  domain: string;
  /**
   * The time this record was first observed.
   */
  firstSeen: Date;
  /**
   * The time this record was last observed.
   */
  lastSeen: Date;
  /**
   * Either A or AAAA.
   */
  recordType: DnsIpResolutionRecordRecordType;
};

/** @internal */
export const DnsIpResolutionRecordRecordType$inboundSchema: z.ZodType<
  DnsIpResolutionRecordRecordType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DnsIpResolutionRecordRecordType);

/** @internal */
export const DnsIpResolutionRecord$inboundSchema: z.ZodType<
  DnsIpResolutionRecord,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  first_seen: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  last_seen: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  record_type: DnsIpResolutionRecordRecordType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "first_seen": "firstSeen",
    "last_seen": "lastSeen",
    "record_type": "recordType",
  });
});

export function dnsIpResolutionRecordFromJSON(
  jsonString: string,
): SafeParseResult<DnsIpResolutionRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DnsIpResolutionRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DnsIpResolutionRecord' from JSON`,
  );
}
