/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Either A or AAAA.
 */
export const DnsIpResolutionRangeRecordRecordType = {
  A: "A",
  Aaaa: "AAAA",
} as const;
/**
 * Either A or AAAA.
 */
export type DnsIpResolutionRangeRecordRecordType = OpenEnum<
  typeof DnsIpResolutionRangeRecordRecordType
>;

export type DnsIpResolutionRangeRecord = {
  /**
   * The domain name that resolved to this IP.
   */
  domain: string;
  /**
   * The time this record was first observed.
   */
  firstSeen: Date;
  /**
   * The time this record was last observed.
   */
  lastSeen: Date;
  /**
   * Either A or AAAA.
   */
  recordType: DnsIpResolutionRangeRecordRecordType;
};

/** @internal */
export const DnsIpResolutionRangeRecordRecordType$inboundSchema: z.ZodType<
  DnsIpResolutionRangeRecordRecordType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DnsIpResolutionRangeRecordRecordType);

/** @internal */
export const DnsIpResolutionRangeRecord$inboundSchema: z.ZodType<
  DnsIpResolutionRangeRecord,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  first_seen: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  last_seen: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  record_type: DnsIpResolutionRangeRecordRecordType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "first_seen": "firstSeen",
    "last_seen": "lastSeen",
    "record_type": "recordType",
  });
});

export function dnsIpResolutionRangeRecordFromJSON(
  jsonString: string,
): SafeParseResult<DnsIpResolutionRangeRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DnsIpResolutionRangeRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DnsIpResolutionRangeRecord' from JSON`,
  );
}
