/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DnsResolutionRecord,
  DnsResolutionRecord$inboundSchema,
} from "./dnsresolutionrecord.js";

export type DnsNameResolutionBoundResponse = {
  /**
   * The domain name that was queried.
   */
  name: string;
  /**
   * A token that can be used to retrieve the next page of records.
   */
  nextPageToken: string;
  /**
   * The list of DNS records.
   */
  records: Array<DnsResolutionRecord> | null;
  /**
   * The number of records that exist in total across all pages.
   */
  totalRecords: number;
};

/** @internal */
export const DnsNameResolutionBoundResponse$inboundSchema: z.ZodType<
  DnsNameResolutionBoundResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  next_page_token: z.string(),
  records: z.nullable(z.array(DnsResolutionRecord$inboundSchema)),
  total_records: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "next_page_token": "nextPageToken",
    "total_records": "totalRecords",
  });
});

export function dnsNameResolutionBoundResponseFromJSON(
  jsonString: string,
): SafeParseResult<DnsNameResolutionBoundResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DnsNameResolutionBoundResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DnsNameResolutionBoundResponse' from JSON`,
  );
}
