/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DotnetNegotiateStream = {
  hresult?: string | undefined;
  messageIdName?: string | undefined;
  protocolVersion?: string | undefined;
  supportedMechOids?: Array<string> | null | undefined;
  supportedMechs?: Array<string> | null | undefined;
};

/** @internal */
export const DotnetNegotiateStream$inboundSchema: z.ZodType<
  DotnetNegotiateStream,
  z.ZodTypeDef,
  unknown
> = z.object({
  hresult: z.string().optional(),
  message_id_name: z.string().optional(),
  protocol_version: z.string().optional(),
  supported_mech_oids: z.nullable(z.array(z.string())).optional(),
  supported_mechs: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "message_id_name": "messageIdName",
    "protocol_version": "protocolVersion",
    "supported_mech_oids": "supportedMechOids",
    "supported_mechs": "supportedMechs",
  });
});

export function dotnetNegotiateStreamFromJSON(
  jsonString: string,
): SafeParseResult<DotnetNegotiateStream, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DotnetNegotiateStream$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DotnetNegotiateStream' from JSON`,
  );
}
