/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DSACryptographicKey = {
  g?: string | undefined;
  p?: string | undefined;
  q?: string | undefined;
  y?: string | undefined;
};

/** @internal */
export const DSACryptographicKey$inboundSchema: z.ZodType<
  DSACryptographicKey,
  z.ZodTypeDef,
  unknown
> = z.object({
  g: z.string().optional(),
  p: z.string().optional(),
  q: z.string().optional(),
  y: z.string().optional(),
});

export function dsaCryptographicKeyFromJSON(
  jsonString: string,
): SafeParseResult<DSACryptographicKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DSACryptographicKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DSACryptographicKey' from JSON`,
  );
}
