/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DvrIpPartitionCapability = {
  maxPartitionNumber?: number | undefined;
  supported?: boolean | undefined;
};

/** @internal */
export const DvrIpPartitionCapability$inboundSchema: z.ZodType<
  DvrIpPartitionCapability,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_partition_number: z.number().int().optional(),
  supported: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "max_partition_number": "maxPartitionNumber",
  });
});

export function dvrIpPartitionCapabilityFromJSON(
  jsonString: string,
): SafeParseResult<DvrIpPartitionCapability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DvrIpPartitionCapability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DvrIpPartitionCapability' from JSON`,
  );
}
