/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ECDSACryptographicKey = {
  b?: string | undefined;
  curve?: string | undefined;
  gx?: string | undefined;
  gy?: string | undefined;
  length?: number | undefined;
  n?: string | undefined;
  p?: string | undefined;
  pub?: string | undefined;
  x?: string | undefined;
  y?: string | undefined;
};

/** @internal */
export const ECDSACryptographicKey$inboundSchema: z.ZodType<
  ECDSACryptographicKey,
  z.ZodTypeDef,
  unknown
> = z.object({
  b: z.string().optional(),
  curve: z.string().optional(),
  gx: z.string().optional(),
  gy: z.string().optional(),
  length: z.number().int().optional(),
  n: z.string().optional(),
  p: z.string().optional(),
  pub: z.string().optional(),
  x: z.string().optional(),
  y: z.string().optional(),
});

export function ecdsaCryptographicKeyFromJSON(
  jsonString: string,
): SafeParseResult<ECDSACryptographicKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ECDSACryptographicKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ECDSACryptographicKey' from JSON`,
  );
}
