/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ElasticSearchResultsNodeInfoNodesNodeDataModules = {
  className?: string | undefined;
  desc?: string | undefined;
  elasticVersion?: string | undefined;
  extPlugins?: Array<string> | null | undefined;
  hasNativeCtrl?: boolean | undefined;
  javaVersion?: string | undefined;
  name?: string | undefined;
  version?: string | undefined;
};

/** @internal */
export const ElasticSearchResultsNodeInfoNodesNodeDataModules$inboundSchema:
  z.ZodType<
    ElasticSearchResultsNodeInfoNodesNodeDataModules,
    z.ZodTypeDef,
    unknown
  > = z.object({
    class_name: z.string().optional(),
    desc: z.string().optional(),
    elastic_version: z.string().optional(),
    ext_plugins: z.nullable(z.array(z.string())).optional(),
    has_native_ctrl: z.boolean().optional(),
    java_version: z.string().optional(),
    name: z.string().optional(),
    version: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "class_name": "className",
      "elastic_version": "elasticVersion",
      "ext_plugins": "extPlugins",
      "has_native_ctrl": "hasNativeCtrl",
      "java_version": "javaVersion",
    });
  });

export function elasticSearchResultsNodeInfoNodesNodeDataModulesFromJSON(
  jsonString: string,
): SafeParseResult<
  ElasticSearchResultsNodeInfoNodesNodeDataModules,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ElasticSearchResultsNodeInfoNodesNodeDataModules$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ElasticSearchResultsNodeInfoNodesNodeDataModules' from JSON`,
  );
}
