/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ElasticSearchResultsNodeInfoNodesNodeDataJVM = {
  gc?: Array<string> | null | undefined;
  inputArgs?: Array<string> | null | undefined;
  memoryPools?: Array<string> | null | undefined;
  startTime?: string | undefined;
  startTimeMs?: number | undefined;
  version?: string | undefined;
  vmName?: string | undefined;
  vmVendor?: string | undefined;
  vmVersion?: string | undefined;
};

/** @internal */
export const ElasticSearchResultsNodeInfoNodesNodeDataJVM$inboundSchema:
  z.ZodType<
    ElasticSearchResultsNodeInfoNodesNodeDataJVM,
    z.ZodTypeDef,
    unknown
  > = z.object({
    gc: z.nullable(z.array(z.string())).optional(),
    input_args: z.nullable(z.array(z.string())).optional(),
    memory_pools: z.nullable(z.array(z.string())).optional(),
    start_time: z.string().optional(),
    start_time_ms: z.number().int().optional(),
    version: z.string().optional(),
    vm_name: z.string().optional(),
    vm_vendor: z.string().optional(),
    vm_version: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "input_args": "inputArgs",
      "memory_pools": "memoryPools",
      "start_time": "startTime",
      "start_time_ms": "startTimeMs",
      "vm_name": "vmName",
      "vm_vendor": "vmVendor",
      "vm_version": "vmVersion",
    });
  });

export function elasticSearchResultsNodeInfoNodesNodeDataJVMFromJSON(
  jsonString: string,
): SafeParseResult<
  ElasticSearchResultsNodeInfoNodesNodeDataJVM,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ElasticSearchResultsNodeInfoNodesNodeDataJVM$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ElasticSearchResultsNodeInfoNodesNodeDataJVM' from JSON`,
  );
}
