/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs,
  ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs$inboundSchema,
} from "./elasticsearchresultsnodeinfoclustercombinedinfoindicesdocs.js";
import {
  ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore,
  ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore$inboundSchema,
} from "./elasticsearchresultsnodeinfoclustercombinedinfoindicesstore.js";

export type ElasticSearchResultsNodeInfoClusterCombinedInfoIndices = {
  count?: number | undefined;
  docs?: ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs | undefined;
  store?:
    | ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore
    | undefined;
};

/** @internal */
export const ElasticSearchResultsNodeInfoClusterCombinedInfoIndices$inboundSchema:
  z.ZodType<
    ElasticSearchResultsNodeInfoClusterCombinedInfoIndices,
    z.ZodTypeDef,
    unknown
  > = z.object({
    count: z.number().int().optional(),
    docs:
      ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesDocs$inboundSchema
        .optional(),
    store:
      ElasticSearchResultsNodeInfoClusterCombinedInfoIndicesStore$inboundSchema
        .optional(),
  });

export function elasticSearchResultsNodeInfoClusterCombinedInfoIndicesFromJSON(
  jsonString: string,
): SafeParseResult<
  ElasticSearchResultsNodeInfoClusterCombinedInfoIndices,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ElasticSearchResultsNodeInfoClusterCombinedInfoIndices$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ElasticSearchResultsNodeInfoClusterCombinedInfoIndices' from JSON`,
  );
}
