/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EthereumVersion = {
  client?: string | undefined;
  compiler?: string | undefined;
  platform?: string | undefined;
  trailing?: string | undefined;
  version?: string | undefined;
};

/** @internal */
export const EthereumVersion$inboundSchema: z.ZodType<
  EthereumVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  client: z.string().optional(),
  compiler: z.string().optional(),
  platform: z.string().optional(),
  trailing: z.string().optional(),
  version: z.string().optional(),
});

export function ethereumVersionFromJSON(
  jsonString: string,
): SafeParseResult<EthereumVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EthereumVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EthereumVersion' from JSON`,
  );
}
