/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ExtractedEndpointDataAnalyticsService,
  ExtractedEndpointDataAnalyticsService$inboundSchema,
} from "./extractedendpointdataanalyticsservice.js";
import {
  ExtractedEndpointDataCopyright,
  ExtractedEndpointDataCopyright$inboundSchema,
} from "./extractedendpointdatacopyright.js";

export type ExtractedEndpointData = {
  analyticsServices?:
    | Array<ExtractedEndpointDataAnalyticsService>
    | null
    | undefined;
  copyrights?: Array<ExtractedEndpointDataCopyright> | null | undefined;
  ipAddresses?: Array<string> | null | undefined;
  languages?: Array<string> | null | undefined;
  links?: Array<string> | null | undefined;
  macAddresses?: Array<string> | null | undefined;
};

/** @internal */
export const ExtractedEndpointData$inboundSchema: z.ZodType<
  ExtractedEndpointData,
  z.ZodTypeDef,
  unknown
> = z.object({
  analytics_services: z.nullable(
    z.array(ExtractedEndpointDataAnalyticsService$inboundSchema),
  ).optional(),
  copyrights: z.nullable(z.array(ExtractedEndpointDataCopyright$inboundSchema))
    .optional(),
  ip_addresses: z.nullable(z.array(z.string())).optional(),
  languages: z.nullable(z.array(z.string())).optional(),
  links: z.nullable(z.array(z.string())).optional(),
  mac_addresses: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "analytics_services": "analyticsServices",
    "ip_addresses": "ipAddresses",
    "mac_addresses": "macAddresses",
  });
});

export function extractedEndpointDataFromJSON(
  jsonString: string,
): SafeParseResult<ExtractedEndpointData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtractedEndpointData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtractedEndpointData' from JSON`,
  );
}
