/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FieldDiff = {
  new?: string | undefined;
  old?: string | undefined;
};

/** @internal */
export const FieldDiff$inboundSchema: z.ZodType<
  FieldDiff,
  z.ZodTypeDef,
  unknown
> = z.object({
  new: z.string().optional(),
  old: z.string().optional(),
});

export function fieldDiffFromJSON(
  jsonString: string,
): SafeParseResult<FieldDiff, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FieldDiff$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldDiff' from JSON`,
  );
}
