/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ForwardDnsResolved = {
  name?: string | undefined;
  resolveTime?: string | undefined;
};

/** @internal */
export const ForwardDnsResolved$inboundSchema: z.ZodType<
  ForwardDnsResolved,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  resolve_time: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "resolve_time": "resolveTime",
  });
});

/** @internal */
export type ForwardDnsResolved$Outbound = {
  name?: string | undefined;
  resolve_time?: string | undefined;
};

/** @internal */
export const ForwardDnsResolved$outboundSchema: z.ZodType<
  ForwardDnsResolved$Outbound,
  z.ZodTypeDef,
  ForwardDnsResolved
> = z.object({
  name: z.string().optional(),
  resolveTime: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    resolveTime: "resolve_time",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ForwardDnsResolved$ {
  /** @deprecated use `ForwardDnsResolved$inboundSchema` instead. */
  export const inboundSchema = ForwardDnsResolved$inboundSchema;
  /** @deprecated use `ForwardDnsResolved$outboundSchema` instead. */
  export const outboundSchema = ForwardDnsResolved$outboundSchema;
  /** @deprecated use `ForwardDnsResolved$Outbound` instead. */
  export type Outbound = ForwardDnsResolved$Outbound;
}

export function forwardDnsResolvedToJSON(
  forwardDnsResolved: ForwardDnsResolved,
): string {
  return JSON.stringify(
    ForwardDnsResolved$outboundSchema.parse(forwardDnsResolved),
  );
}

export function forwardDnsResolvedFromJSON(
  jsonString: string,
): SafeParseResult<ForwardDnsResolved, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForwardDnsResolved$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForwardDnsResolved' from JSON`,
  );
}
