/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { GopherItem, GopherItem$inboundSchema } from "./gopheritem.js";

export type Gopher = {
  body?: string | undefined;
  items?: Array<GopherItem> | null | undefined;
  title?: string | undefined;
};

/** @internal */
export const Gopher$inboundSchema: z.ZodType<Gopher, z.ZodTypeDef, unknown> = z
  .object({
    body: z.string().optional(),
    items: z.nullable(z.array(GopherItem$inboundSchema)).optional(),
    title: z.string().optional(),
  });

export function gopherFromJSON(
  jsonString: string,
): SafeParseResult<Gopher, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Gopher$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Gopher' from JSON`,
  );
}
