/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  HikvisionPlatformLibrary,
  HikvisionPlatformLibrary$inboundSchema,
} from "./hikvisionplatformlibrary.js";

export type HikvisionPlatform = {
  libraries?: Array<HikvisionPlatformLibrary> | null | undefined;
  name?: string | undefined;
};

/** @internal */
export const HikvisionPlatform$inboundSchema: z.ZodType<
  HikvisionPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  libraries: z.nullable(z.array(HikvisionPlatformLibrary$inboundSchema))
    .optional(),
  name: z.string().optional(),
});

export function hikvisionPlatformFromJSON(
  jsonString: string,
): SafeParseResult<HikvisionPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HikvisionPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HikvisionPlatform' from JSON`,
  );
}
