/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HttpRepeatedHeaders = {
  /**
   * The values provided in the corresponding header.
   */
  headers?: Array<string> | null | undefined;
};

/** @internal */
export const HttpRepeatedHeaders$inboundSchema: z.ZodType<
  HttpRepeatedHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({
  headers: z.nullable(z.array(z.string())).optional(),
});

export function httpRepeatedHeadersFromJSON(
  jsonString: string,
): SafeParseResult<HttpRepeatedHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HttpRepeatedHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HttpRepeatedHeaders' from JSON`,
  );
}
