/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IcapOptionsResponse = {
  allow204?: boolean | undefined;
  icapVersion?: string | undefined;
  istag?: string | undefined;
  maxConnections?: number | undefined;
  methods?: Array<string> | null | undefined;
  optionsTtl?: number | undefined;
  preview?: number | undefined;
  serverHeader?: string | undefined;
  service?: string | undefined;
  serviceId?: string | undefined;
  statusCode?: number | undefined;
  statusText?: string | undefined;
};

/** @internal */
export const IcapOptionsResponse$inboundSchema: z.ZodType<
  IcapOptionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  allow_204: z.boolean().optional(),
  icap_version: z.string().optional(),
  istag: z.string().optional(),
  max_connections: z.number().int().optional(),
  methods: z.nullable(z.array(z.string())).optional(),
  options_ttl: z.number().int().optional(),
  preview: z.number().int().optional(),
  server_header: z.string().optional(),
  service: z.string().optional(),
  service_id: z.string().optional(),
  status_code: z.number().int().optional(),
  status_text: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "allow_204": "allow204",
    "icap_version": "icapVersion",
    "max_connections": "maxConnections",
    "options_ttl": "optionsTtl",
    "server_header": "serverHeader",
    "service_id": "serviceId",
    "status_code": "statusCode",
    "status_text": "statusText",
  });
});

export function icapOptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<IcapOptionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IcapOptionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IcapOptionsResponse' from JSON`,
  );
}
