/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Influxdb = {
  build?: string | undefined;
  setupAllowed?: boolean | undefined;
  version?: string | undefined;
};

/** @internal */
export const Influxdb$inboundSchema: z.ZodType<
  Influxdb,
  z.ZodTypeDef,
  unknown
> = z.object({
  build: z.string().optional(),
  setup_allowed: z.boolean().optional(),
  version: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "setup_allowed": "setupAllowed",
  });
});

export function influxdbFromJSON(
  jsonString: string,
): SafeParseResult<Influxdb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Influxdb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Influxdb' from JSON`,
  );
}
