/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IpmiSessionHeaderAuthType = {
  /**
   * The raw value of the auth_type
   */
  name?: string | undefined;
  /**
   * The raw value of the auth_type
   */
  raw?: number | undefined;
  /**
   * Just the auth type (reserved bits omitted)
   */
  type?: number | undefined;
};

/** @internal */
export const IpmiSessionHeaderAuthType$inboundSchema: z.ZodType<
  IpmiSessionHeaderAuthType,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  raw: z.number().int().optional(),
  type: z.number().int().optional(),
});

export function ipmiSessionHeaderAuthTypeFromJSON(
  jsonString: string,
): SafeParseResult<IpmiSessionHeaderAuthType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpmiSessionHeaderAuthType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpmiSessionHeaderAuthType' from JSON`,
  );
}
