/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IppAttribute = {
  name?: string | undefined;
  valueTag?: number | undefined;
};

/** @internal */
export const IppAttribute$inboundSchema: z.ZodType<
  IppAttribute,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  value_tag: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "value_tag": "valueTag",
  });
});

export function ippAttributeFromJSON(
  jsonString: string,
): SafeParseResult<IppAttribute, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IppAttribute$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IppAttribute' from JSON`,
  );
}
