/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { FieldDiff, FieldDiff$inboundSchema } from "./fielddiff.js";
import { JarmScan, JarmScan$inboundSchema } from "./jarmscan.js";

export type JarmScanned = {
  diff?: { [k: string]: FieldDiff } | undefined;
  scan?: JarmScan | undefined;
};

/** @internal */
export const JarmScanned$inboundSchema: z.ZodType<
  JarmScanned,
  z.ZodTypeDef,
  unknown
> = z.object({
  diff: z.record(FieldDiff$inboundSchema).optional(),
  scan: JarmScan$inboundSchema.optional(),
});

export function jarmScannedFromJSON(
  jsonString: string,
): SafeParseResult<JarmScanned, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JarmScanned$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JarmScanned' from JSON`,
  );
}
