/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { JenkinsBuild, JenkinsBuild$inboundSchema } from "./jenkinsbuild.js";

export type JenkinsJob = {
  description?: string | undefined;
  lastBuild?: JenkinsBuild | undefined;
  name?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const JenkinsJob$inboundSchema: z.ZodType<
  JenkinsJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  last_build: JenkinsBuild$inboundSchema.optional(),
  name: z.string().optional(),
  url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "last_build": "lastBuild",
  });
});

export function jenkinsJobFromJSON(
  jsonString: string,
): SafeParseResult<JenkinsJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JenkinsJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JenkinsJob' from JSON`,
  );
}
