/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Krpc = {
  pingResponseId?: string | undefined;
};

/** @internal */
export const Krpc$inboundSchema: z.ZodType<Krpc, z.ZodTypeDef, unknown> = z
  .object({
    ping_response_id: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "ping_response_id": "pingResponseId",
    });
  });

export function krpcFromJSON(
  jsonString: string,
): SafeParseResult<Krpc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Krpc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Krpc' from JSON`,
  );
}
