/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  KubernetesRoleRule,
  KubernetesRoleRule$inboundSchema,
} from "./kubernetesrolerule.js";

export type KubernetesRole = {
  name?: string | undefined;
  /**
   * Rules set for this role.
   */
  rules?: Array<KubernetesRoleRule> | null | undefined;
};

/** @internal */
export const KubernetesRole$inboundSchema: z.ZodType<
  KubernetesRole,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  rules: z.nullable(z.array(KubernetesRoleRule$inboundSchema)).optional(),
});

export function kubernetesRoleFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesRole' from JSON`,
  );
}
