/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type KubernetesEndpointSubsetPort = {
  name?: string | undefined;
  port?: number | undefined;
  protocol?: string | undefined;
};

/** @internal */
export const KubernetesEndpointSubsetPort$inboundSchema: z.ZodType<
  KubernetesEndpointSubsetPort,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  port: z.number().int().optional(),
  protocol: z.string().optional(),
});

export function kubernetesEndpointSubsetPortFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesEndpointSubsetPort, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesEndpointSubsetPort$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesEndpointSubsetPort' from JSON`,
  );
}
