/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LdapAttribute = {
  /**
   * Name of the LDAP attribute in the root DN
   */
  name?: string | undefined;
  /**
   * Values for the respective LDAP attribute
   */
  values?: Array<string> | null | undefined;
};

/** @internal */
export const LdapAttribute$inboundSchema: z.ZodType<
  LdapAttribute,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  values: z.nullable(z.array(z.string())).optional(),
});

export function ldapAttributeFromJSON(
  jsonString: string,
): SafeParseResult<LdapAttribute, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LdapAttribute$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LdapAttribute' from JSON`,
  );
}
