/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LpdMessage = {
  body?: string | undefined;
  status?: number | undefined;
};

/** @internal */
export const LpdMessage$inboundSchema: z.ZodType<
  LpdMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string().optional(),
  status: z.number().int().optional(),
});

export function lpdMessageFromJSON(
  jsonString: string,
): SafeParseResult<LpdMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LpdMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LpdMessage' from JSON`,
  );
}
