/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MalloryAIOpinionAttributes = {
  associatedMalware?: Array<string> | null | undefined;
  associatedThreatActors?: Array<string> | null | undefined;
  associatedVulnerabilities?: Array<string> | null | undefined;
  tags?: Array<string> | null | undefined;
};

/** @internal */
export const MalloryAIOpinionAttributes$inboundSchema: z.ZodType<
  MalloryAIOpinionAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  associated_malware: z.nullable(z.array(z.string())).optional(),
  associated_threat_actors: z.nullable(z.array(z.string())).optional(),
  associated_vulnerabilities: z.nullable(z.array(z.string())).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "associated_malware": "associatedMalware",
    "associated_threat_actors": "associatedThreatActors",
    "associated_vulnerabilities": "associatedVulnerabilities",
  });
});

export function malloryAIOpinionAttributesFromJSON(
  jsonString: string,
): SafeParseResult<MalloryAIOpinionAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MalloryAIOpinionAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MalloryAIOpinionAttributes' from JSON`,
  );
}
