/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MalloryAIObservable = {
  attributes?: string | undefined;
  createdAt?: string | undefined;
  description?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
  updatedAt?: string | undefined;
  uuid?: string | undefined;
};

/** @internal */
export const MalloryAIObservable$inboundSchema: z.ZodType<
  MalloryAIObservable,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional(),
  name: z.string().optional(),
  type: z.string().optional(),
  updated_at: z.string().optional(),
  uuid: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function malloryAIObservableFromJSON(
  jsonString: string,
): SafeParseResult<MalloryAIObservable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MalloryAIObservable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MalloryAIObservable' from JSON`,
  );
}
