/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type McpTool = {
  description?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const McpTool$inboundSchema: z.ZodType<McpTool, z.ZodTypeDef, unknown> =
  z.object({
    description: z.string().optional(),
    name: z.string().optional(),
  });

export function mcpToolFromJSON(
  jsonString: string,
): SafeParseResult<McpTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => McpTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'McpTool' from JSON`,
  );
}
