/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NmeaNmeaMessage,
  NmeaNmeaMessage$inboundSchema,
} from "./nmeanmeamessage.js";

export type Nmea = {
  messages?: Array<NmeaNmeaMessage> | null | undefined;
};

/** @internal */
export const Nmea$inboundSchema: z.ZodType<Nmea, z.ZodTypeDef, unknown> = z
  .object({
    messages: z.nullable(z.array(NmeaNmeaMessage$inboundSchema)).optional(),
  });

export function nmeaFromJSON(
  jsonString: string,
): SafeParseResult<Nmea, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Nmea$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Nmea' from JSON`,
  );
}
