/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NtripDataStream = {
  authentication?: Array<string> | null | undefined;
  bitrate?: number | undefined;
  carrierInfo?: string | undefined;
  casterMountPoint?: string | undefined;
  compressionOrEncryption?: string | undefined;
  countryCode?: string | undefined;
  dataFormat?: string | undefined;
  fee?: boolean | undefined;
  formatDetails?: string | undefined;
  generator?: string | undefined;
  latitude?: string | undefined;
  longitude?: string | undefined;
  misc?: string | undefined;
  navSystem?: string | undefined;
  network?: string | undefined;
  nmea?: boolean | undefined;
  solution?: string | undefined;
  sourceIdentifier?: string | undefined;
};

/** @internal */
export const NtripDataStream$inboundSchema: z.ZodType<
  NtripDataStream,
  z.ZodTypeDef,
  unknown
> = z.object({
  authentication: z.nullable(z.array(z.string())).optional(),
  bitrate: z.number().int().optional(),
  carrier_info: z.string().optional(),
  caster_mount_point: z.string().optional(),
  compression_or_encryption: z.string().optional(),
  country_code: z.string().optional(),
  data_format: z.string().optional(),
  fee: z.boolean().optional(),
  format_details: z.string().optional(),
  generator: z.string().optional(),
  latitude: z.string().optional(),
  longitude: z.string().optional(),
  misc: z.string().optional(),
  nav_system: z.string().optional(),
  network: z.string().optional(),
  nmea: z.boolean().optional(),
  solution: z.string().optional(),
  source_identifier: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "carrier_info": "carrierInfo",
    "caster_mount_point": "casterMountPoint",
    "compression_or_encryption": "compressionOrEncryption",
    "country_code": "countryCode",
    "data_format": "dataFormat",
    "format_details": "formatDetails",
    "nav_system": "navSystem",
    "source_identifier": "sourceIdentifier",
  });
});

export function ntripDataStreamFromJSON(
  jsonString: string,
): SafeParseResult<NtripDataStream, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NtripDataStream$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NtripDataStream' from JSON`,
  );
}
