/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Openvpn = {
  acceptsV1?: boolean | undefined;
  acceptsV2?: boolean | undefined;
};

/** @internal */
export const Openvpn$inboundSchema: z.ZodType<Openvpn, z.ZodTypeDef, unknown> =
  z.object({
    accepts_v1: z.boolean().optional(),
    accepts_v2: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      "accepts_v1": "acceptsV1",
      "accepts_v2": "acceptsV2",
    });
  });

export function openvpnFromJSON(
  jsonString: string,
): SafeParseResult<Openvpn, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Openvpn$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Openvpn' from JSON`,
  );
}
