/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationMember,
  OrganizationMember$inboundSchema,
} from "./organizationmember.js";
import {
  PaginationInfo,
  PaginationInfo$inboundSchema,
} from "./paginationinfo.js";

export type OrganizationMembersList = {
  /**
   * The list of members in the organization.
   */
  members: Array<OrganizationMember> | null;
  pagination: PaginationInfo;
};

/** @internal */
export const OrganizationMembersList$inboundSchema: z.ZodType<
  OrganizationMembersList,
  z.ZodTypeDef,
  unknown
> = z.object({
  members: z.nullable(z.array(OrganizationMember$inboundSchema)),
  pagination: PaginationInfo$inboundSchema,
});

export function organizationMembersListFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationMembersList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationMembersList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationMembersList' from JSON`,
  );
}
