/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Pop3 = {
  /**
   * The server's response to the STARTTLS command.
   */
  startTls?: string | undefined;
};

/** @internal */
export const Pop3$inboundSchema: z.ZodType<Pop3, z.ZodTypeDef, unknown> = z
  .object({
    start_tls: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "start_tls": "startTls",
    });
  });

export function pop3FromJSON(
  jsonString: string,
): SafeParseResult<Pop3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pop3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pop3' from JSON`,
  );
}
