/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcStatementsPdsLocation = {
  language?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const QcStatementsPdsLocation$inboundSchema: z.ZodType<
  QcStatementsPdsLocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  language: z.string().optional(),
  url: z.string().optional(),
});

export function qcStatementsPdsLocationFromJSON(
  jsonString: string,
): SafeParseResult<QcStatementsPdsLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcStatementsPdsLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcStatementsPdsLocation' from JSON`,
  );
}
