/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RdpCertificateInfo,
  RdpCertificateInfo$inboundSchema,
} from "./rdpcertificateinfo.js";
import {
  RdpConnectResponse,
  RdpConnectResponse$inboundSchema,
} from "./rdpconnectresponse.js";
import {
  RdpProtocolFlags,
  RdpProtocolFlags$inboundSchema,
} from "./rdpprotocolflags.js";
import {
  RdpSecurityProtocol,
  RdpSecurityProtocol$inboundSchema,
} from "./rdpsecurityprotocol.js";
import { RdpVersion, RdpVersion$inboundSchema } from "./rdpversion.js";

export type Rdp = {
  certificateInfo?: RdpCertificateInfo | undefined;
  connectResponse?: RdpConnectResponse | undefined;
  protocolFlags?: RdpProtocolFlags | undefined;
  selectedSecurityProtocol?: RdpSecurityProtocol | undefined;
  version?: RdpVersion | undefined;
  x224CcPduDstref?: number | undefined;
  x224CcPduSrcref?: number | undefined;
};

/** @internal */
export const Rdp$inboundSchema: z.ZodType<Rdp, z.ZodTypeDef, unknown> = z
  .object({
    certificate_info: RdpCertificateInfo$inboundSchema.optional(),
    connect_response: RdpConnectResponse$inboundSchema.optional(),
    protocol_flags: RdpProtocolFlags$inboundSchema.optional(),
    selected_security_protocol: RdpSecurityProtocol$inboundSchema.optional(),
    version: RdpVersion$inboundSchema.optional(),
    x224_cc_pdu_dstref: z.number().int().optional(),
    x224_cc_pdu_srcref: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      "certificate_info": "certificateInfo",
      "connect_response": "connectResponse",
      "protocol_flags": "protocolFlags",
      "selected_security_protocol": "selectedSecurityProtocol",
      "x224_cc_pdu_dstref": "x224CcPduDstref",
      "x224_cc_pdu_srcref": "x224CcPduSrcref",
    });
  });

export function rdpFromJSON(
  jsonString: string,
): SafeParseResult<Rdp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Rdp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Rdp' from JSON`,
  );
}
