/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InvestigationFileUpload,
  InvestigationFileUpload$inboundSchema,
} from "./investigationfileupload.js";

export type ResponseEnvelopeInvestigationFileUpload = {
  result?: InvestigationFileUpload | undefined;
};

/** @internal */
export const ResponseEnvelopeInvestigationFileUpload$inboundSchema: z.ZodType<
  ResponseEnvelopeInvestigationFileUpload,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: InvestigationFileUpload$inboundSchema.optional(),
});

export function responseEnvelopeInvestigationFileUploadFromJSON(
  jsonString: string,
): SafeParseResult<
  ResponseEnvelopeInvestigationFileUpload,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ResponseEnvelopeInvestigationFileUpload$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ResponseEnvelopeInvestigationFileUpload' from JSON`,
  );
}
