/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebpropertyAsset,
  WebpropertyAsset$inboundSchema,
} from "./webpropertyasset.js";

export type ResponseEnvelopeListWebpropertyAsset = {
  result?: Array<WebpropertyAsset> | null | undefined;
};

/** @internal */
export const ResponseEnvelopeListWebpropertyAsset$inboundSchema: z.ZodType<
  ResponseEnvelopeListWebpropertyAsset,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: z.nullable(z.array(WebpropertyAsset$inboundSchema)).optional(),
});

export function responseEnvelopeListWebpropertyAssetFromJSON(
  jsonString: string,
): SafeParseResult<ResponseEnvelopeListWebpropertyAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ResponseEnvelopeListWebpropertyAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseEnvelopeListWebpropertyAsset' from JSON`,
  );
}
