/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ListCollectionsResponseV1,
  ListCollectionsResponseV1$inboundSchema,
} from "./listcollectionsresponsev1.js";

export type ResponseEnvelopeListCollectionsResponseV1 = {
  result?: ListCollectionsResponseV1 | undefined;
};

/** @internal */
export const ResponseEnvelopeListCollectionsResponseV1$inboundSchema: z.ZodType<
  ResponseEnvelopeListCollectionsResponseV1,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: ListCollectionsResponseV1$inboundSchema.optional(),
});

export function responseEnvelopeListCollectionsResponseV1FromJSON(
  jsonString: string,
): SafeParseResult<
  ResponseEnvelopeListCollectionsResponseV1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ResponseEnvelopeListCollectionsResponseV1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ResponseEnvelopeListCollectionsResponseV1' from JSON`,
  );
}
