/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { HostAsset, HostAsset$inboundSchema } from "./hostasset.js";

export type ResponseEnvelopeListHostAsset = {
  result?: Array<HostAsset> | null | undefined;
};

/** @internal */
export const ResponseEnvelopeListHostAsset$inboundSchema: z.ZodType<
  ResponseEnvelopeListHostAsset,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: z.nullable(z.array(HostAsset$inboundSchema)).optional(),
});

export function responseEnvelopeListHostAssetFromJSON(
  jsonString: string,
): SafeParseResult<ResponseEnvelopeListHostAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseEnvelopeListHostAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseEnvelopeListHostAsset' from JSON`,
  );
}
