/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RustdeskRendezvousConfigUpdate = {
  rendezvousServers?: Array<string> | null | undefined;
  serial?: number | undefined;
};

/** @internal */
export const RustdeskRendezvousConfigUpdate$inboundSchema: z.ZodType<
  RustdeskRendezvousConfigUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  rendezvous_servers: z.nullable(z.array(z.string())).optional(),
  serial: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "rendezvous_servers": "rendezvousServers",
  });
});

export function rustdeskRendezvousConfigUpdateFromJSON(
  jsonString: string,
): SafeParseResult<RustdeskRendezvousConfigUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RustdeskRendezvousConfigUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RustdeskRendezvousConfigUpdate' from JSON`,
  );
}
