/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SapientError, SapientError$inboundSchema } from "./sapienterror.js";
import {
  SapientRegistrationAck,
  SapientRegistrationAck$inboundSchema,
} from "./sapientregistrationack.js";

export type Sapient = {
  error?: SapientError | undefined;
  payload?: string | undefined;
  registrationAck?: SapientRegistrationAck | undefined;
  unknown?: string | undefined;
};

/** @internal */
export const Sapient$inboundSchema: z.ZodType<Sapient, z.ZodTypeDef, unknown> =
  z.object({
    error: SapientError$inboundSchema.optional(),
    payload: z.string().optional(),
    registration_ack: SapientRegistrationAck$inboundSchema.optional(),
    unknown: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "registration_ack": "registrationAck",
    });
  });

export function sapientFromJSON(
  jsonString: string,
): SafeParseResult<Sapient, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sapient$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sapient' from JSON`,
  );
}
