/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Scpi = {
  firmware?: string | undefined;
  manufacturer?: string | undefined;
  model?: string | undefined;
  serial?: string | undefined;
};

/** @internal */
export const Scpi$inboundSchema: z.ZodType<Scpi, z.ZodTypeDef, unknown> = z
  .object({
    firmware: z.string().optional(),
    manufacturer: z.string().optional(),
    model: z.string().optional(),
    serial: z.string().optional(),
  });

export function scpiFromJSON(
  jsonString: string,
): SafeParseResult<Scpi, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Scpi$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Scpi' from JSON`,
  );
}
