/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Screenshot = {
  extractedText?: string | undefined;
  handle?: string | undefined;
};

/** @internal */
export const Screenshot$inboundSchema: z.ZodType<
  Screenshot,
  z.ZodTypeDef,
  unknown
> = z.object({
  extracted_text: z.string().optional(),
  handle: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "extracted_text": "extractedText",
  });
});

/** @internal */
export type Screenshot$Outbound = {
  extracted_text?: string | undefined;
  handle?: string | undefined;
};

/** @internal */
export const Screenshot$outboundSchema: z.ZodType<
  Screenshot$Outbound,
  z.ZodTypeDef,
  Screenshot
> = z.object({
  extractedText: z.string().optional(),
  handle: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    extractedText: "extracted_text",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Screenshot$ {
  /** @deprecated use `Screenshot$inboundSchema` instead. */
  export const inboundSchema = Screenshot$inboundSchema;
  /** @deprecated use `Screenshot$outboundSchema` instead. */
  export const outboundSchema = Screenshot$outboundSchema;
  /** @deprecated use `Screenshot$Outbound` instead. */
  export type Outbound = Screenshot$Outbound;
}

export function screenshotToJSON(screenshot: Screenshot): string {
  return JSON.stringify(Screenshot$outboundSchema.parse(screenshot));
}

export function screenshotFromJSON(
  jsonString: string,
): SafeParseResult<Screenshot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Screenshot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Screenshot' from JSON`,
  );
}
