/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type Security = {
  personalAccessToken: string;
};

/** @internal */
export type Security$Outbound = {
  PersonalAccessToken: string;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  personalAccessToken: z.string(),
}).transform((v) => {
  return remap$(v, {
    personalAccessToken: "PersonalAccessToken",
  });
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
