/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SignedCertificateTimestampSignature = {
  hashAlgorithm?: string | undefined;
  signature?: string | undefined;
  signatureAlgorithm?: string | undefined;
};

/** @internal */
export const SignedCertificateTimestampSignature$inboundSchema: z.ZodType<
  SignedCertificateTimestampSignature,
  z.ZodTypeDef,
  unknown
> = z.object({
  hash_algorithm: z.string().optional(),
  signature: z.string().optional(),
  signature_algorithm: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "hash_algorithm": "hashAlgorithm",
    "signature_algorithm": "signatureAlgorithm",
  });
});

export function signedCertificateTimestampSignatureFromJSON(
  jsonString: string,
): SafeParseResult<SignedCertificateTimestampSignature, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SignedCertificateTimestampSignature$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SignedCertificateTimestampSignature' from JSON`,
  );
}
