/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TelexperTlxp = {
  frameType?: string | undefined;
  imageHeightPx?: number | undefined;
  imageWidthPx?: number | undefined;
};

/** @internal */
export const TelexperTlxp$inboundSchema: z.ZodType<
  TelexperTlxp,
  z.ZodTypeDef,
  unknown
> = z.object({
  frame_type: z.string().optional(),
  image_height_px: z.number().int().optional(),
  image_width_px: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "frame_type": "frameType",
    "image_height_px": "imageHeightPx",
    "image_width_px": "imageWidthPx",
  });
});

export function telexperTlxpFromJSON(
  jsonString: string,
): SafeParseResult<TelexperTlxp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TelexperTlxp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TelexperTlxp' from JSON`,
  );
}
