/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { MalloryAI, MalloryAI$inboundSchema } from "./malloryai.js";

export type ThirdParty = {
  /**
   * Threat intelligence records from MalloryAI.
   */
  mallory?: Array<MalloryAI> | null | undefined;
};

/** @internal */
export const ThirdParty$inboundSchema: z.ZodType<
  ThirdParty,
  z.ZodTypeDef,
  unknown
> = z.object({
  mallory: z.nullable(z.array(MalloryAI$inboundSchema)).optional(),
});

export function thirdPartyFromJSON(
  jsonString: string,
): SafeParseResult<ThirdParty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThirdParty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThirdParty' from JSON`,
  );
}
