/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Thrulay = {
  negotiatedWindowBytes?: number | undefined;
  negotiationRejectReason?: string | undefined;
  protocolVersion?: string | undefined;
};

/** @internal */
export const Thrulay$inboundSchema: z.ZodType<Thrulay, z.ZodTypeDef, unknown> =
  z.object({
    negotiated_window_bytes: z.number().int().optional(),
    negotiation_reject_reason: z.string().optional(),
    protocol_version: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "negotiated_window_bytes": "negotiatedWindowBytes",
      "negotiation_reject_reason": "negotiationRejectReason",
      "protocol_version": "protocolVersion",
    });
  });

export function thrulayFromJSON(
  jsonString: string,
): SafeParseResult<Thrulay, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Thrulay$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Thrulay' from JSON`,
  );
}
