/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ServiceId, ServiceId$inboundSchema } from "./serviceid.js";
import {
  TrackedScanScanTargetHostnamePort,
  TrackedScanScanTargetHostnamePort$inboundSchema,
} from "./trackedscanscantargethostnameport.js";
import {
  TrackedScanScanTargetHostPort,
  TrackedScanScanTargetHostPort$inboundSchema,
} from "./trackedscanscantargethostport.js";
import { WebOrigin, WebOrigin$inboundSchema } from "./weborigin.js";

export type TrackedScanScanTarget = {
  hostPort?: TrackedScanScanTargetHostPort | undefined;
  hostnamePort?: TrackedScanScanTargetHostnamePort | undefined;
  serviceId?: ServiceId | undefined;
  webOrigin?: WebOrigin | undefined;
};

/** @internal */
export const TrackedScanScanTarget$inboundSchema: z.ZodType<
  TrackedScanScanTarget,
  z.ZodTypeDef,
  unknown
> = z.object({
  host_port: TrackedScanScanTargetHostPort$inboundSchema.optional(),
  hostname_port: TrackedScanScanTargetHostnamePort$inboundSchema.optional(),
  service_id: ServiceId$inboundSchema.optional(),
  web_origin: WebOrigin$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "host_port": "hostPort",
    "hostname_port": "hostnamePort",
    "service_id": "serviceId",
    "web_origin": "webOrigin",
  });
});

export function trackedScanScanTargetFromJSON(
  jsonString: string,
): SafeParseResult<TrackedScanScanTarget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TrackedScanScanTarget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TrackedScanScanTarget' from JSON`,
  );
}
