/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnitronicsPcom = {
  bufferSize?: string | undefined;
  hardwareVersion?: string | undefined;
  model?: string | undefined;
  modelExecutor?: string | undefined;
  modelOpExecutor?: string | undefined;
  name?: string | undefined;
  osBuild?: string | undefined;
  osVersion?: string | undefined;
  uniqueId?: number | undefined;
  unitId?: string | undefined;
};

/** @internal */
export const UnitronicsPcom$inboundSchema: z.ZodType<
  UnitronicsPcom,
  z.ZodTypeDef,
  unknown
> = z.object({
  buffer_size: z.string().optional(),
  hardware_version: z.string().optional(),
  model: z.string().optional(),
  model_executor: z.string().optional(),
  model_op_executor: z.string().optional(),
  name: z.string().optional(),
  os_build: z.string().optional(),
  os_version: z.string().optional(),
  unique_id: z.number().int().optional(),
  unit_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "buffer_size": "bufferSize",
    "hardware_version": "hardwareVersion",
    "model_executor": "modelExecutor",
    "model_op_executor": "modelOpExecutor",
    "os_build": "osBuild",
    "os_version": "osVersion",
    "unique_id": "uniqueId",
    "unit_id": "unitId",
  });
});

export function unitronicsPcomFromJSON(
  jsonString: string,
): SafeParseResult<UnitronicsPcom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnitronicsPcom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnitronicsPcom' from JSON`,
  );
}
