/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Tag visibility and management settings. `private` tags are only visible to and editable by organization admins. `shared` tags are visible to and editable by all organization members.
 */
export const UpdateTagInputBodyPrivacy = {
  Private: "private",
  Shared: "shared",
} as const;
/**
 * Tag visibility and management settings. `private` tags are only visible to and editable by organization admins. `shared` tags are visible to and editable by all organization members.
 */
export type UpdateTagInputBodyPrivacy = ClosedEnum<
  typeof UpdateTagInputBodyPrivacy
>;

export type UpdateTagInputBody = {
  /**
   * New description.
   */
  description?: string | undefined;
  /**
   * New display name. Must be unique within the organization.
   */
  name?: string | undefined;
  /**
   * Tag visibility and management settings. `private` tags are only visible to and editable by organization admins. `shared` tags are visible to and editable by all organization members.
   */
  privacy?: UpdateTagInputBodyPrivacy | undefined;
};

/** @internal */
export const UpdateTagInputBodyPrivacy$outboundSchema: z.ZodNativeEnum<
  typeof UpdateTagInputBodyPrivacy
> = z.nativeEnum(UpdateTagInputBodyPrivacy);

/** @internal */
export type UpdateTagInputBody$Outbound = {
  description?: string | undefined;
  name?: string | undefined;
  privacy?: string | undefined;
};

/** @internal */
export const UpdateTagInputBody$outboundSchema: z.ZodType<
  UpdateTagInputBody$Outbound,
  z.ZodTypeDef,
  UpdateTagInputBody
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
  privacy: UpdateTagInputBodyPrivacy$outboundSchema.optional(),
});

export function updateTagInputBodyToJSON(
  updateTagInputBody: UpdateTagInputBody,
): string {
  return JSON.stringify(
    UpdateTagInputBody$outboundSchema.parse(updateTagInputBody),
  );
}
