/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NoticeReference,
  NoticeReference$inboundSchema,
} from "./noticereference.js";

export type UserNotice = {
  explicitText?: string | undefined;
  noticeReference?: NoticeReference | undefined;
};

/** @internal */
export const UserNotice$inboundSchema: z.ZodType<
  UserNotice,
  z.ZodTypeDef,
  unknown
> = z.object({
  explicit_text: z.string().optional(),
  notice_reference: NoticeReference$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "explicit_text": "explicitText",
    "notice_reference": "noticeReference",
  });
});

export function userNoticeFromJSON(
  jsonString: string,
): SafeParseResult<UserNotice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserNotice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserNotice' from JSON`,
  );
}
