/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VncKeyValue = {
  name?: string | undefined;
  value?: number | undefined;
};

/** @internal */
export const VncKeyValue$inboundSchema: z.ZodType<
  VncKeyValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  value: z.number().int().optional(),
});

export function vncKeyValueFromJSON(
  jsonString: string,
): SafeParseResult<VncKeyValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VncKeyValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VncKeyValue' from JSON`,
  );
}
