/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WsDiscovery = {
  addresses?: Array<string> | null | undefined;
  metadataVersion?: number | undefined;
  scopes?: Array<string> | null | undefined;
  types?: Array<string> | null | undefined;
};

/** @internal */
export const WsDiscovery$inboundSchema: z.ZodType<
  WsDiscovery,
  z.ZodTypeDef,
  unknown
> = z.object({
  addresses: z.nullable(z.array(z.string())).optional(),
  metadata_version: z.number().int().optional(),
  scopes: z.nullable(z.array(z.string())).optional(),
  types: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "metadata_version": "metadataVersion",
  });
});

export function wsDiscoveryFromJSON(
  jsonString: string,
): SafeParseResult<WsDiscovery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WsDiscovery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WsDiscovery' from JSON`,
  );
}
